name: Telco CI

on:
  push:
    branches:
      - main

jobs:

  train-model:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install mlflow pandas scikit-learn joblib

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run .